name: Test Suite
run-name: Running test suite
on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: calculadora

      - name: Run tests
        run: npm test
        working-directory: calculadora 